# Generated by Django 4.1.3 on 2022-11-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_icecream_alter_review_options_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecream',
            old_name='brand',
            new_name='name',
        ),
    ]
