# Generated by Django 4.1.3 on 2022-11-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_brand_icecream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='iceCream',
            field=models.ManyToManyField(to='main_app.icecream'),
        ),
    ]
